"""Add FK User to Model

Revision ID: 993706a50742
Revises: 2e2446020757
Create Date: 2022-04-27 22:49:23.589076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993706a50742'
down_revision = '2e2446020757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
